# Generated by Django 5.0.1 on 2026-02-16 06:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='2-20자의 한글, 영문, 숫자, 언더스코어', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임은 2-20자의 한글, 영문, 숫자, 언더스코어만 가능합니다', regex='^[a-zA-Z0-9가-힣_]{2,20}$')], verbose_name='닉네임')),
                ('phone', models.CharField(help_text='예: 010-1234-5678', max_length=15, validators=[django.core.validators.RegexValidator(message='올바른 전화번호 형식이 아닙니다 (예: 010-1234-5678)', regex='^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$')], verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필 목록',
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
